# Generated by Django 5.2.8 on 2025-11-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
    ]
